/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    Package: typeof import('./src/components/packege/Package.vue')['default']
    PackageVersion: typeof import('./src/components/packege/PackageVersion.vue')['default']
    PackageVersions: typeof import('./src/components/packege/PackageVersions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/ui/Search.vue')['default']
  }
}
