/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Modal: typeof import('./src/components/ui/Modal.vue')['default']
    Package: typeof import('./src/components/package/Package.vue')['default']
    Packages: typeof import('./src/components/package/Packages.vue')['default']
    Packagess: typeof import('./src/components/package/Packagess.vue')['default']
    PackageVersion: typeof import('./src/components/package/PackageVersion.vue')['default']
    PackageVersions: typeof import('./src/components/package/PackageVersions.vue')['default']
    Pagination: typeof import('./src/components/pagination/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/search/Search.vue')['default']
  }
}
